version: "3.2"

services: 
  db:
    image: mongo:4.4.2
    container_name: db
    restart: always
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: loginDB

  node-app:
    build: .
    container_name: node-app
    command: npm run dev
    depends_on: 
      - db
    ports:
      - "3333:3333"
    volumes: 
      - .:/home/nicalves/Docker

   
